config/routes.rb
Rails.application.routes.draw do

  root "notes#index"

  devise_for :users, controllers: { registrations: 'users/registrations' } 
  
  resources :users do
    post 'follow', on: :member, to: 'follows#create'
    delete 'unfollow', on: :member, to: 'follows#destroy'
  end
  
  resources :notes do
    post 'like', on: :member, to: 'likes#create'
    delete 'unlike', on: :member, to: 'likes#destroy'
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :likes
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @users = User.all
    @notes = Note.all
    if current_user
      @follows = Follow.where(follower_id: current_user.id)
    end
  end

  def new
    @note = Note.new
  end

  def create
    note = current_user.notes.new(note_params)
    note.save
    redirect_to notes_path
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update;
    note = Note.find(params[:id])
    if note.update(note_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
  <% @notes.each do |note| %>
    <p class= "notes_each"><strong> Note title:</strong> <%= note.title %></p> 
    <p class= "notes_each"><strong>Note body:</strong>  <%= note.body %></p> 
    <p class= "notes_each"><small>By: <%= note.user.username %></small></p> 
  <div class = "notes_crud">
    <% if current_user == note.user %>
      <%= link_to 'Delete note', note_path(note), method: :delete, data: {confirm:"Delete this note?"} %>
      <%= link_to 'Edit note', edit_note_path(note) %>
    <% end %>
  </div>
  
    <% if current_user %>
      <% if Follow.find_by(following_id: note.user, follower_id: current_user) %>
        <% else %>
    <% if Like.where(note: note, user: current_user) %>
    <% else %>
    <%= link_to 'Unfollow', unfollow_user_path(note.user_id), remote: true, method: :delete %>
  <% end %>
        </div>
      <% end %>
  <div class = "likes">
    <% if Like.find_by(note: note, user: current_user) %>
      <%= link_to "Unlike", unlike_note_path(note), method: :delete %>
        <%= note.likes.count %>    
    <% else %>
      <%= link_to "Like", like_note_path(note), method: :post %>
      <%= note.likes.count %>
    <% end %>
  </div>
    <% else %>
      <br><hr><br>
    <% end %>
  <% end %>
  
<div class="sidebar">
  <% if current_user %>
    <h2>People I am following</h2>

    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem</p>
    <% if @follows == nil %>
      <div>No User You Are Following</div>
    <% else %>
      <% @follows.each do |follow| %>
        <%= follow.following.username %>
        <%= link_to 'Unfollow', unfollow_user_path(follow.following.id), remote: true, method: :delete %>
        <br>
      <% end %>
      <hr>
    <% end %>
    <h3>Users yet to follow</h3>
    <% @users.each do |user| %>
      <% if Follow.find_by(following_id: user, follower_id: current_user) %>
      <% else %>
        <%= user.username %>
        <%= link_to 'Follow', follow_user_path(user), remote: true, method: :post %>
      <% end%>
    <% end %>
  <% else %>
    <h3>All users</h3>
    <% @users.each do |user| %>
      <%= user.username %> <br>
    <% end %>
  <% end %>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= form_for @note, url: note_path, method: :put do |note| %>
  <div><%= note.text_field :title, :maxlength => 200, placeholder: "Your message gist here!"  %></div> 
  <div><%= note.text_area :body, :maxlength => 300, placeholder: "Your message body here!"%></div>
  <%= note.submit %>
<% end %>
<br>
<input type="button" onclick="window.history.go(-1)" value="Go back!" >

app/views/notes/index.html.erb
<h1 class = "title">Welcome ! </h1>

<div id="notes">
  <%= render partial: "note" %>
</div>

app/views/notes/index.js.erb
$('#notes').append('<%= escape_javascript render(@notes) %>');

app/views/notes/new.html.erb
<h1>Create new note here!</h1>

<%= form_for @note, url: notes_path, method: :post do |note| %>
  <%= note.text_field :title, :maxlength => 140, placeholder: "Type your title here!"  %> <br><br>
  <%= note.text_area :body, :maxlength => 300, size: "140x10", placeholder: "Type your note here!"%> <br><br>
  <%= note.submit %>
<% end %>
<br>
<input type="button" value="Back" onclick="history.back()">